### ISSUE TITLE
Replacing OneToOne entity with a em.remove() followed by a new entity causes UniqueContraintViolationException 

### ISSUE THREAD

**Issue by alisd23** [mikro-orm/mikro-orm#2273]
**Describe the bug**
When trying to replace a OneToOne relation by:
1. Calling `em.remove(entity)` on the current one-to-one relation (non-owning side)
2. Assigning a new entity to the same relation, replacing the old one.
3. Calling `em.flush()`

The remove step never occurs, or at least the insert is attempted first (can't be sure as it fails on the insert), causing a `UniqueConstraintViolationException` error.

Thought it might be to do with which is the owning side, but I thought the entity manager would be able to generate a remove, followed by an insert in the same transaction.

**Stack trace**
```
UniqueConstraintViolationException: insert into `discount` (`amount`, `checkout_id`) values (2000, 1) - Duplicate entry '1' for key 'discount_checkout_id_unique'

      at MySqlExceptionConverter.convertException (../node_modules/@mikro-orm/mysql-base/MySqlExceptionConverter.js:33:24)
      at MySqlDriver.convertException (../node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:202:54)
      at ../node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:206:24
      at MySqlDriver.nativeInsert (../node_modules/@mikro-orm/knex/AbstractSqlDriver.js:154:21)
      at ChangeSetPersister.persistNewEntity (../node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:55:21)
      at ChangeSetPersister.executeInserts (../node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:24:13)
      at UnitOfWork.commitCreateChangeSets (../node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:520:9)
      at UnitOfWork.persistToDatabase (../node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:473:13)
      at MySqlConnection.transactional (../node_modules/@mikro-orm/knex/AbstractSqlConnection.js:53:25)
      previous Error: insert into `discount` (`amount`, `checkout_id`) values (2000, 1) - Duplicate entry '1' for key 'discount_checkout_id_unique'
      at Packet.asError (../node_modules/mysql2/lib/packets/packet.js:712:17)
      at Query.execute (../node_modules/mysql2/lib/commands/command.js:28:26)
      at Connection.handlePacket (../node_modules/mysql2/lib/connection.js:425:32)
      at PacketParser.onPacket (../node_modules/mysql2/lib/connection.js:75:12)
      at PacketParser.executeStart (../node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (../node_modules/mysql2/lib/connection.js:82:25)
```

**To Reproduce**
Repo here: https://github.com/alisd23/mikro-orm-issues

### Entities

Checkout 
```ts
@Entity()
export class Checkout {
  @PrimaryKey()
  id: number;

  @OneToOne(() => Discount, discount => discount.checkout, {
    nullable: true,
  })
  discount: Discount | null;
}
```

Discount (owning side)
```ts
@Entity()
export class Discount {
  constructor(amount: number) {
    this.amount = amount;
  }

  @PrimaryKey()
  id: number;

  @OneToOne(() => Checkout, checkout => checkout.discount, {
    nullable: true,
    owner: true
  })
  checkout: Checkout | null;

  @Property()
  amount: number;
}
```

Attempt the following operations:
```ts
// 1. Remove old discount
em.remove(checkout.discount);
// 2. Insert new discount
checkout.discount = new Discount(2000);
// HOWEVER, when flush runs, the removal never happens, or at least the insert is being attempted first,
// causing a unique constraint violation at the SQL level
await em.flush();
```

The **remove stack** looks like this just before persist:
```
Set(1) {
  Discount {
    id: 1,
    checkout: Checkout { id: 1, discount: [Discount] },
    amount: 1000
  }
}
```

And the **persist stack** like this:
```
Set(2) {
  Discount { amount: 2000, checkout: Checkout { id: 1, discount: [Discount] } },
  Checkout { id: 1, discount: Discount { amount: 2000, checkout: [Checkout] } }
}
```

**Expected behavior**
I would expect the following transaction to run:
1. Remove old discount entity
2. Insert new discount entity, with its `checkout_id` field assigned to the checkout.

No modifications to the checkout entity are needed due the discount being the owning side.

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 14.7.1 |
| typescript | 4.4.3 |
| mikro-orm | 4.5.9 |
| your-driver | mysql |

**Comment by klausXR** [comment]
I think I also encountered this.

Also, is the following supposed to work

```js
// Insert a new discount directly
checkout.discount = new Discount(2000);

await em.flush();
```

Without having to remove the old one?

To change the discount, one could implement a method on the `Checkout` entity, however, if you have to call `em.remove(checkout.discount)`, you cannot do it from the entity, unless you accept the entity manager as an argument and call `em.remove()` from the entity method manually.

Intuitively, I expected the following to work, but it doesn't for me, for some reason and I'm wondering if its not meant to be used like this or I misconfigured my entity

```js
const checkout = await checkoutRepository.find(...)

checkout.discount = null

await em.flush() // Expected this to remove the discount from the database, but it doesnt
```

**Comment by B4nan** [comment]
> The checkout had a discount initially, and this is "supposed" to destroy the old record and insert a new one
> checkout.discount = new Discount(2000);

For that you need orphan removal.

https://mikro-orm.io/docs/next/cascading/#orphan-removal

I recently fixed something very similar to this one, but apparently the reproduction here is still valid, will see if we can do something about it.

**Comment by klausXR** [comment]
I tried it, works for 1:M collections but it doesn't seem to work for 1:1 relations, perhaps its the same issue

**Comment by B4nan** [comment]
With m:1/1:m you don't have the unique constrain. The problem is that delete queries are normally issued as the last ones, but in those cases we need to remove before we insert the corresponding entity.

**Comment by B4nan** [comment]
Fixed in v5, I won't be backporting this one as it depends on other changes that are v5 only.

**Comment by klausXR** [comment]
@B4nan can you have a look at this https://github.com/klausXR/mikro-orm-embeddable-m1-fieldName/blob/main/src/index.ts and see if there is anything wrong with the setup, because it doesn't really seem to work. 

I cloned some guy's repository in a rush so the readme is wrong, but trying to set `checkout.discount = null` and flush it throws the Unique constraint validation. it tries to set `discount.checkout_id = null` on line 42

**Comment by B4nan** [comment]
Haven't tried in that repo, but this test is passing in latest master:

```ts
import { Entity, LoadStrategy, MikroORM, OneToOne, PrimaryKey, Property } from '@mikro-orm/core';

@Entity()
export class Checkout {

  @PrimaryKey()
  id!: number;

  // eslint-disable-next-line @typescript-eslint/no-use-before-define
  @OneToOne(() => Discount, discount => discount.checkout, {
    nullable: true,
    orphanRemoval: true,
  })
  discount?: any;

}

@Entity()
export class Discount {

  @PrimaryKey()
  id!: number;

  @OneToOne(() => Checkout, checkout => checkout.discount, {
    nullable: true,
    owner: true,
  })
  checkout?: Checkout;

  @Property()
  amount: number;

  constructor(amount: number) {
    this.amount = amount;
  }

}

describe('Remove entity issue (GH 2273)', () => {
  let orm: MikroORM;

  beforeAll(async () => {
    orm = await MikroORM.init({
      type: 'sqlite',
      dbName: ':memory:',
      entities: [Discount, Checkout],
    });
  });

  beforeEach(async () => {
    await orm.getSchemaGenerator().dropSchema();
    await orm.getSchemaGenerator().createSchema();
    orm.em.clear();
  });

  afterAll(async () => {
    await orm.close();
  });

  it('Should be able to remove discount from checkout', async () => {

    // Creating a checkout with a discount
    const createdCheckout = new Checkout();
    createdCheckout.discount = new Discount(25);

    await orm.em.fork().persistAndFlush(createdCheckout);

    {
      // Remove the discount by setting it to null
      const em = orm.em.fork();
      const checkout = await em.findOneOrFail(Checkout, createdCheckout.id, {
        populate: ['discount'],
        strategy: LoadStrategy.JOINED,
      });

      checkout.discount = null;

      await em.flush();
    }

    {
      // Verify checkout.discount is destroyed
      const em = orm.em.fork();
      const checkout = await em.find(Checkout, createdCheckout.id, {
        populate: ['discount'],
        strategy: LoadStrategy.JOINED,
      });

      console.log('Checkout below should not have a discount');
      console.log(checkout);
    }
  });

});
```

![image](https://user-images.githubusercontent.com/615580/146688230-987a6a5f-2061-4b32-be56-2674231e1555.png)

**Comment by klausXR** [comment]
> 

The repository should be using the latest version also, just tried with your latest changes (  from 580 to 583 ) which is the commit from 40 minutes ago and it still doesn't work

```

[discovery] ORM entity discovery started, using ReflectMetadataProvider
[discovery] - processing entity Checkout
[discovery] - processing entity Discount
[discovery] - entity discovery finished, found 2 entities, took 14 ms
[info] MikroORM successfully connected to database postgres on postgresql://postgres:*****@127.0.0.1:5432
[query] delete from "discount" [took 4 ms]
[query] delete from "checkout" [took 3 ms]
[query] begin
[query] insert into "checkout" default values returning "id" [took 1 ms]
[query] insert into "discount" ("amount", "checkout_id") values (25, 20) returning "id" [took 1 ms]
[query] commit
[query] select "c0"."id", "d1"."id" as "d1__id", "d1"."checkout_id" as "d1__checkout_id", "d1"."amount" as "d1__amount", "d1"."id" as "discount_id" from "checkout" as "c0" left join "discount" as "d1" on "c0"."id" = "d1"."checkout_id" where "c0"."id" = 20 [took 1 ms]
[query] begin
[query] update "discount" set "checkout_id" = NULL where "id" = 22 [took 2 ms]
[query] rollback
(node:15204) UnhandledPromiseRejectionWarning: NotNullConstraintViolationException: update "discount" set "checkout_id" = NULL where "id" = 22 - null value in column "checkout_id" violates not-null constraint
```

This is the output that its yielding. Its late and I'm tired, gonna give it another shot when I have some free time

**Comment by B4nan** [comment]
Oh I see, I left the property as nullable. There is actually another bug, orphan removal is not triggered at all in that case.

**Comment by klausXR** [comment]
> Oh I see, I left the property as nullable. There is actually another bug, orphan removal is not triggered at all in that case.
> 
> edit: should be also fixed in latest v5

Thanks, it seems to be working now. I guess I'll start using V5 directly and not wait for the stable release
